### ISSUE TITLE
Windows 11 UCP fails

### ISSUE THREAD

**Issue by Psychopomp2655** [ermo/s2u_ucp#8]
on my windows 11 system UCP_s2u_ubpacker will not run as intended, I've launch it as admin my real time protect on windows defender is turned off also as to not have it interfere. 

<img width="452" alt="UCP" src="https://github.com/user-attachments/assets/b63e5006-ced3-45a0-8335-04695d3175c6">

**Comment by ermo** [comment]
Do you still hit the issue if you change the install folder of S2U to somewhere outside of the %programfiles% folder?

I haven't touched this in a long time, and I don't have any win11 installs at this point, so I have no idea what changes MS might have made to their OS protection routines since the win7 days where this was originally developed.

**Comment by Psychopomp2655** [comment]
yeah issue persist even when game has been moved out of the programfiles folder, Moved it into my general games folder still won't run correctly. I'm going to try to see if I can get it to work in windows 10 VM. but otherwise still no dice. 
![{6971B1F8-AE47-4F50-9D7A-4F0CA836EA49}](https://github.com/user-attachments/assets/7cb3e932-1cf6-411d-9cf3-7c0e7f01c889)

**Comment by Psychopomp2655** [comment]
not sure if it's any help but the error point to BOOTFLOW.bff which isn't in the s2u_ucp-master folder 
![{9B458027-BCB7-4B9D-A83D-F8B04171E409}](https://github.com/user-attachments/assets/547bb56e-c0ad-4012-b7c7-97d61b34da98)

**Comment by ermo** [comment]
Which version of the game are you using?

**Comment by Psychopomp2655** [comment]
not sure of the Game version it should be the last update version, I'm running it though the EA app had a look in properties to see it if told me which version which it doesn't anyway to see in the game files or in gmae?

**Comment by ermo** [comment]
Did you by any chance neglect to follow the README/wiki instructions re. which patches need to be installed...?

You _may_ be able to right-click the SHIFT2U.exe and view its properties there.

**Comment by Psychopomp2655** [comment]
I have read it, I just wasn't certain of the game version upon your comment, I'm on 1.02 and yes I did follow the read me. it's a known issue that some user have problems running the mod on win11 systems. even being listed on other mods for the game

**Comment by ermo** [comment]
> I have read it, I just wasn't certain of the game version upon your comment, I'm on 1.02 and yes I did follow the read me. it's a known issue that some user have problems running the mod on win11 systems. even being listed on other mods for the game

Cheers. I find it interesting that the present mod -- and its issues -- are a known thing, and that other mods build upon it. Do the other mods also use JSGME?

**Comment by Psychopomp2655** [comment]
they do also JSGME 

this is what you see first on the mod page: (https://nfsmods.xyz/mod/4128)
Requires UCP to be installed (https://github.com/ermo/s2u_ucp/wiki)
Beware Windows 11 users; the OS has a very concerning issue of not allowing to use cmd or powershell at all, even in admin mode, so the installation of the ucp can fail
On top of that there's a chance of JSGME not working at all

**Comment by ermo** [comment]
Does it make _any_ difference if you use the newest version of quickbms.exe from here: https://github.com/LittleBigBug/QuickBMS/releases ? The idea is that you rename the old version and drop in the new one.

Note: I have not actually checked if that version is any different than the one shipped with UCP (though it likely is, since it's from 2024).

**Comment by R04Rager** [comment]
Okay, I was having the same issue (win 11 user), tried the newest QuickBMS files, but had the same problem. But then just to rule it out, I ran the unpacker without using running as admin, and it worked! It finished the unpacking and everything else after worked as it was supposed to. Now I don't know if it was just running without being admin that did it, or if it also needed the newer quickbms, but at least it's possible to pass this problem.

**Comment by Psychopomp2655** [comment]
wonderful it unpacks now thank you for the help

**Comment by ermo** [comment]
@R04Rager @Psychopomp2655 If the two of you could narrow it down to what the actual solution is on win11, that would be helpful to future win11 users of the mod?

**Comment by BoneDuster96** [comment]
dont click right and run with admin. simple doubleclick (windows ask for admin rights) click yes and have fun. i think it had to do with edited UAC by microsoft. now its a little bit like sudo and su from linux. 

My OS: Windows 11 24H2 Build: 26100
