### ISSUE TITLE
Game crashes when I start a race with add-on cars

### ISSUE THREAD

**Issue by Oldmode512** [ermo/s2u_ucp#9]
I've installed a nascar mod (https://www.youtube.com/watch?v=hDw3EqP8oJo) that includes Ford, Chevrolet and Toyota. These add-on cars are displaying ok in car lot, but when I fucking try to start a race with any of these cars, MY GAME FUCKING CRASHES. What can I do to fix this issue? I'm literally raging rn ;~;

**Comment by ermo** [comment]
@FadyFunker What was the problem, and how did you fix it?
